# Usa a imagem oficial do Miniconda como base
FROM continuumio/miniconda3
 
# Define o diretório de trabalho no contentor
WORKDIR /src
 
# Copia o ficheiro de definição do ambiente para o contentor
COPY conda-minimal.yaml .
COPY config config 
COPY src src
 
# Cria o ambiente conda a partir do ficheiro conda.yaml # 

RUN conda env create -f conda-minimal.yaml

EXPOSE 5003

# Executa a aplicação FastAPI # 

CMD conda run --no-capture-output -n OML python src/main.py