services:

  mlflow-tracking-server:
    image: ghcr.io/mlflow/mlflow
    command: mlflow ui --port 5000 --host 0.0.0.0 --backend-store-uri /mlruns --artifacts-destination /mlruns
    volumes:
      - c:/Users/User/python_programing/OML-trabalho-master/mlruns:/mlruns
    container_name: tracking-mlflow
    ports:
      - "5000:5000"

  rumos-bank-service:
    build:
      context: .
      dockerfile: Dockerfile.Service 
      tags:
        - rumos-bank-service
        - ghcr.io/filipalagoa/rumos-bank-service 
    image: rumos-bank-service
    container_name: rumos-bank-service-app
    ports:
      - "5003:5003"
