services:

  mlflow-tracking-server:
    image: ghcr.io/mlflow/mlflow
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri /mlflow/mlruns --default-artifact-root /mlflow/mlruns
    volumes:
     - ./modelos:/mlruns
    container_name: tracking
    ports:
     - "5000:5000"


 # Rumos Bank service:
  rumos-banck-service:
    build:
      context: .
      dockerfile: Dockerfile.Service 
      tags:
        - rumos-bank-service
        - ghcr.io/filipalagoa/rumos-bank-service 
    image: rumos-bank-service
    container_name: service
    ports:
      - "5002:5002"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow-tracking-server:5000
